
/*
* This Java source file was generated by the Gradle 'init' task.
*/
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;
class AppTest {
    @Test
    void testJson()  {

        Gson gson = new Gson();
        Reader reader = null;
        try {
            reader = Files.newBufferedReader(Paths.get("app/src/test/resources/data.json"));
            BufferedReader readJson = new BufferedReader(reader);
            Quotes[] result = gson.fromJson(readJson, Quotes[].class);
            String expected = "Today's Quote: Quote:  “Ask no questions, and you'll be told no lies.�? author: Charles Dickens";
            Quotes output = result[1];

            assertEquals(expected,output);

        } catch (IOException e) {
            System.out.println("file not found ... " + e.getMessage());

        }
    }


}
