/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import com.google.gson.*;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class App {
    public static void main(String[] args){
        Gson gson = new Gson();
        try {

            Reader reader = new FileReader("app/src/main/resources/data.json");
            Quotes[] recentQuotes = gson.fromJson(reader, Quotes[].class);
            int index = (int)(Math.random()*recentQuotes.length);
            System.out.println(recentQuotes[index]);
        } catch (IOException ex) {
            System.out.println("file not found ..at this path: " + ex.getMessage());
        }
    }
}